name: Index GitHub Advisories

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # index every 6 hours

env:
  ADVISORY_PATH: advisories/nuget-advisories.json
    
jobs:
  index-database:
    runs-on: [ ubuntu-22.04 ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: ./repo

      - name: Index GitHub Advisory Database
        shell: bash

        run: |
          # Shallow copy the advisory database
          git clone --depth 1 --filter=blob:none --sparse https://github.com/github/advisory-database
          cd advisory-database
          git sparse-checkout set advisories/github-reviewed # only care about reviewed advisories
          cd advisories/github-reviewed

          echo "Starting indexing of NuGet advisories"

          docsPath="${GITHUB_WORKSPACE}/repo/docs/${ADVISORY_PATH}"
          publicPath="${GITHUB_WORKSPACE}/repo/public/${ADVISORY_PATH}"

          # Find all NuGet-related vulnerabilities
          find -type f -name "*.json" -exec cat {} + \
            | jq -r '. as $root
              | .affected[] 
              | select((.package.ecosystem | ascii_downcase) == "nuget" and .ranges) 
              | $root.severity[0] 
                  + { "id": $root.id, "severity": $root.database_specific.severity, "package": .package.name } 
                  + (reduce .ranges[0].events[] as $e ({}; . + $e))' \
            | jq -cs '.' \
            > "$docsPath"

          # Keep the build-time advisories in-sync
          cp "$docsPath" "$publicPath"

          advisoryCount=$(jq -r length < "$docsPath")
          echo "Successfully indexed ${advisoryCount} advisories"

      - name: Commit to Repository
        shell: bash
        run: |
          cd "${GITHUB_WORKSPACE}/repo"

          set +e # disable exit-on-error for the diff command
          git diff --quiet "*${ADVISORY_PATH}"
          unchanged=$?
          set -e # re-enable exit-on-error

          if [[ $unchanged -eq 0 ]]; then
            echo "No changes detected in '${GITHUB_WORKSPACE}/repo/docs/${ADVISORY_PATH}'"
          else
            echo "Updating the repository advisory index"

            git config user.name "$GITHUB_ACTOR"
            git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

            git add "*${ADVISORY_PATH}"
            git commit -m "(auto): updated the NuGet advisories index"
            git push
          fi
